import glyphNameFormatter

r = glyphNameFormatter.unicodeRangeNames.getAllRangeNames()
r.sort()
print(r)


['Adlam', 'Aegean Numbers', 'Ahom', 
	'Alchemical Symbols', 'Alphabetic Presentation Forms', 
	'Anatolian Hieroglyphs', 
	'Ancient Greek Musical Notation', 'Ancient Greek Numbers', 'Ancient Symbols', 
	'Arabic', 'Arabic Extended-A', 'Arabic Mathematical Alphabetic Symbols', 'Arabic Presentation Forms-A', 
	'Arabic Presentation Forms-B', 'Arabic Supplement', 
	'Armenian', 'Arrows', 'Avestan', 'Balinese', 'Bamum', 'Bamum Supplement', 
	'Basic Latin', 'Bassa Vah', 'Batak', 'Bengali', 'Bhaiksuki', 'Block Elements', 
	'Bopomofo', 'Bopomofo Extended', 'Box Drawing', 'Brahmi', 'Braille Patterns', 'Buginese', 'Buhid', 
	'Byzantine Musical Symbols', 'CJK Compatibility', 'CJK Compatibility Forms', 
	'CJK Compatibility Ideographs', 'CJK Compatibility Ideographs Supplement', 'CJK Radicals Supplement', 
	'CJK Strokes', 'CJK Symbols and Punctuation', 'CJK Unified Ideographs', 
	'CJK Unified Ideographs Extension A', 'CJK Unified Ideographs Extension B', 
	'CJK Unified Ideographs Extension C', 'CJK Unified Ideographs Extension D', 
	'CJK Unified Ideographs Extension E', 'CJK Unified Ideographs Extension F', 
	'Carian', 'Caucasian Albanian', 'Chakma', 'Cham', 'Cherokee', 'Cherokee Supplement', 
	'Chess Symbols', 'Combining Diacritical Marks', 'Combining Diacritical Marks Extended', 
	'Combining Diacritical Marks Supplement', 'Combining Diacritical Marks for Symbols', 
	'Combining Half Marks', 'Common Indic Number Forms', 'Control Pictures', 
	'Coptic', 'Coptic Epact Numbers', 'Counting Rod Numerals', 'Cuneiform', 
	'Cuneiform Numbers and Punctuation', 'Currency Symbols', 'Cypriot Syllabary', 
	'Cyrillic', 'Cyrillic Extended-A', 'Cyrillic Extended-B', 'Cyrillic Extended-C', 'Cyrillic Supplement', 
	'Deseret', 'Devanagari', 'Devanagari Extended', 'Dingbats', 'Dogra', 'Domino Tiles', 
	'Duployan', 'Early Dynastic Cuneiform', 'Egyptian Hieroglyph Format Controls', 
	'Egyptian Hieroglyphs', 'Elbasan', 'Elymaic', 'Emoticons', 'Enclosed Alphanumeric Supplement', 
	'Enclosed Alphanumerics', 'Enclosed CJK Letters and Months', 'Enclosed Ideographic Supplement', 
	'Ethiopic', 'Ethiopic Extended', 'Ethiopic Extended-A', 'Ethiopic Supplement', 
	'General Punctuation', 'Geometric Shapes', 'Geometric Shapes Extended', 'Georgian', 'Georgian Extended',
	 'Georgian Supplement', 'Glagolitic', 'Glagolitic Supplement', 'Gothic', 'Grantha', 'Greek Extended', 
	 'Greek and Coptic', 'Gujarati', 'Gunjala Gondi', 'Gurmukhi', 'Halfwidth and Fullwidth Forms', 
	 'Hangul Compatibility Jamo', 'Hangul Jamo', 'Hangul Jamo Extended-A', 'Hangul Jamo Extended-B', 
	 'Hangul Syllables', 'Hanifi Rohingya', 'Hanunoo', 'Hatran', 'Hebrew', 'High Private Use Surrogates', 
	 'High Surrogates', 'Hiragana', 'IPA Extensions', 'Ideographic Description Characters', 
	 'Ideographic Symbols and Punctuation', 'Imperial Aramaic', 'Indic Siyaq Numbers', 
	 'Inscriptional Pahlavi', 'Inscriptional Parthian', 'Javanese', 'Kaithi', 'Kana Extended-A', 
	 'Kana Supplement', 'Kanbun', 'Kangxi Radicals', 'Kannada', 'Katakana', 'Katakana Phonetic Extensions', 
	 'Kayah Li', 'Kharoshthi', 'Khmer', 'Khmer Symbols', 'Khojki', 'Khudawadi', 'Lao', 
	 'Latin Extended Additional', 'Latin Extended-A', 'Latin Extended-B', 'Latin Extended-C', 
	 'Latin Extended-D', 'Latin Extended-E', 'Latin-1 Supplement', 'Lepcha', 'Letterlike Symbols', 
	 'Limbu', 'Linear A', 'Linear B Ideograms', 'Linear B Syllabary', 'Lisu', 'Low Surrogates', 'Lycian', 
	 'Lydian', 'Mahajani', 'Mahjong Tiles', 'Makasar', 'Malayalam', 'Mandaic', 'Manichaean', 'Marchen', 
	 'Masaram Gondi', 'Mathematical Alphanumeric Symbols', 'Mathematical Operators', 'Mayan Numerals', 
	 'Medefaidrin', 'Meetei Mayek', 'Meetei Mayek Extensions', 'Mende Kikakui', 
	 'Meroitic Cursive', 'Meroitic Hieroglyphs', 'Miao', 'Miscellaneous Mathematical Symbols-A', 
	 'Miscellaneous Mathematical Symbols-B', 'Miscellaneous Symbols', 'Miscellaneous Symbols and Arrows', 
	 'Miscellaneous Symbols and Pictographs', 'Miscellaneous Technical', 'Modi', 'Modifier Tone Letters', 
	 'Mongolian', 'Mongolian Supplement', 'Mro', 'Multani', 'Musical Symbols', 'Myanmar', 
	 'Myanmar Extended-A', 'Myanmar Extended-B', 'NKo', 'Nabataean', 'Nandinagari', 'New Tai Lue', 'Newa', 
	 'Number Forms', 'Nushu', 'Nyiakeng Puachue Hmong', 'Ogham', 'Ol Chiki', 'Old Hungarian', 'Old Italic', 
	 'Old North Arabian', 'Old Permic', 'Old Persian', 'Old Sogdian', 'Old South Arabian', 'Old Turkic', 
	 'Optical Character Recognition', 'Oriya', 'Ornamental Dingbats', 'Osage', 'Osmanya', 
	 'Ottoman Siyaq Numbers', 'Pahawh Hmong', 'Palmyrene', 'Pau Cin Hau', 'Phags-pa', 'Phaistos Disc',
	  'Phoenician', 'Phonetic Extensions', 'Phonetic Extensions Supplement', 'Playing Cards', 
	  'Private Use Area', 'Psalter Pahlavi', 'Rejang', 'Rumi Numeral Symbols', 'Runic', 
	  'Samaritan', 'Saurashtra', 'Sharada', 'Shavian', 'Shorthand Format Controls', 'Siddham', 'Sinhala', 
	  'Sinhala Archaic Numbers', 'Small Form Variants', 'Small Kana Extension', 'Sogdian', 'Sora Sompeng', 
	  'Soyombo', 'Spacing Modifier Letters', 'Specials', 'Sundanese', 'Sundanese Supplement', 
	  'Superscripts and Subscripts', 'Supplemental Arrows-A', 'Supplemental Arrows-B', 
	  'Supplemental Arrows-C', 'Supplemental Mathematical Operators', 'Supplemental Punctuation', 
	  'Supplemental Symbols and Pictographs', 'Supplementary Private Use Area-A', 
	  'Supplementary Private Use Area-B', 'Sutton SignWriting', 'Syloti Nagri', 
	  'Symbols and Pictographs Extended-A', 'Syriac', 'Syriac Supplement', 'Tagalog', 'Tagbanwa', 
	  'Tags', 'Tai Le', 'Tai Tham', 'Tai Viet', 'Tai Xuan Jing Symbols', 'Takri', 
	  'Tamil', 'Tamil Supplement', 'Tangut', 'Tangut Components', 'Telugu', 'Thaana', 'Thai', 
	  'Tibetan', 'Tifinagh', 'Tirhuta', 'Transport and Map Symbols', 'Ugaritic', 
	  'Unified Canadian Aboriginal Syllabics', 'Unified Canadian Aboriginal Syllabics Extended', 'Vai',
	   'Variation Selectors', 'Variation Selectors Supplement', 'Vedic Extensions', 'Vertical Forms', 
	   'Wancho', 'Warang Citi', 'Yi Radicals', 'Yi Syllables', 'Yijing Hexagram Symbols', 'Zanabazar Square']

